name: compile
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
env:
  LATEX_ROOT: cv
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install nokogiri
          # Add any other gem installations or setup commands here

      - name: Generate bibliometrics
        run: ruby scholar_scraper.rb

      - name: Build latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.LATEX_ROOT }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Build publication list
        run: latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape publication_list.tex

      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%dT%H%M%S')"

      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: ./${{ env.LATEX_ROOT }}/${{ env.LATEX_ROOT }}.pdf

      - name: Upload Publications artifact
        uses: actions/upload-artifact@v4
        with:
          name: publications
          path: ./${{ env.LATEX_ROOT }}/publications_list.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}'
          release_name: "CV and Publications Release"
          body: "This release includes the compiled CV and publications."
          draft: false
          prerelease: false

      - name: Upload CV to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path-to-cv-directory/cv.pdf
          asset_name: cv.pdf
          asset_content_type: application/pdf

      - name: Upload Publications to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path-to-publications-directory/publications.pdf
          asset_name: publications.pdf
          asset_content_type: application/pdf